function robot_const = addVisLink(robot_const, frame, handle, R, t, param, props)
    % ADDVISLINK
    %
    % robot_const = addVisLink(robot_const, frame, handle, R, t, param, props)
        
    robot_const.vis.links(frame+1) = struct('handle', handle, ...
                                            'R', R, ...
                                            't', t, ...
                                            'param', param, ...
                                            'props', {props});
end